# Generated by Django 4.2.7 on 2024-02-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='سربرگ محصول')),
                ('name', models.CharField(max_length=30, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('link_img', models.CharField(max_length=500, verbose_name='لینک محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('is_active', models.BooleanField(default=False, verbose_name='محصول موجود است')),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
